# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
- main

pool:
  vmImage: ubuntu-22.04

steps:
- script: |
    echo "Setting JAVA_HOME to Java 17"
    export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
    export PATH=$JAVA_HOME/bin:$PATH
    java -version
    mvn -version
  displayName: 'Set Java 17'

- script: |
    export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
    export PATH=$JAVA_HOME/bin:$PATH
    mvn -B -X -e -U clean package -Pdist -Pindex
  displayName: 'Maven Build'

- task: NexusIqPipelineTask@2
  inputs:
    nexusIqService: 'int-test.sonatype.app'
    applicationId: 'maria-test-app'
    stage: 'Build'
    reachabilityNamespaces: 'org.sonatype.lifecycle.jenkins.examples.callflow'
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'bomxray.log'
    targetPath: '**/bomxray.log' 
